In [1]:
import numpy as np
from   trax import layers as tl
from   trax import fastmath, shapes

In [2]:
!pip3 list | grep trax

trax                     1.3.5
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -m pip install --upgrade pip' command.


In [3]:
# Layers
# Create a trax layer:
relu = tl.Relu()

print('name:', relu.name)
print('expected inputs:', relu.n_in)
print('promised outputs:', relu.n_out)

name: Relu
expected inputs: 1
promised outputs: 1


In [4]:
# input
x = np.array([-2, -1, 0, 1, 2])
print('Inputs:', x)

# out
y = relu(x)
print('Outputs:', y)

Inputs: [-2 -1  0  1  2]
Outputs: [0 0 0 1 2]


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/lib/xla_bridge.py:130: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')


In [5]:
concat = tl.Concatenate()
concat.name, concat.n_in, concat.n_out

('Concatenate', 2, 1)

In [6]:
x1 = np.array([-10, -20, -30])
x2 = x1 / -10
print(x1)
print(x2)

y = concat([x1, x2])
y

[-10 -20 -30]
[1. 2. 3.]


DeviceArray([-10., -20., -30.,   1.,   2.,   3.], dtype=float32)

In [7]:
concat_3 = tl.Concatenate(n_items=3)
concat_3.name, concat_3.n_in, concat_3.n_out

('Concatenate', 3, 1)

In [8]:
x3 = x2 * 0.99
y = concat_3([x1, x2, x3])
y

DeviceArray([-10.  , -20.  , -30.  ,   1.  ,   2.  ,   3.  ,   0.99,
               1.98,   2.97], dtype=float32)

In [9]:
norm = tl.LayerNorm()
x = np.array([0, 1, 2, 3], dtype='float')
norm.init(shapes.signature(x))

print(x.shape, type(x.shape))
print(shapes.signature(x), type(shapes.signature(x)))

(4,) <class 'tuple'>
ShapeDtype{shape:(4,), dtype:float64} <class 'trax.shapes.ShapeDtype'>


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/lax/lax.py:6188: UserWarning: Explicitly requested dtype float64 requested in ones is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  warnings.warn(msg.format(dtype, fun_name , truncated_dtype))
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/lax/lax.py:6188: UserWarning: Explicitly requested dtype float64 requested in zeros is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  warnings.warn(msg.format(dtype, fun_name , truncated_dtype))


In [10]:
norm.name, norm.n_in, norm.n_out

('LayerNorm', 1, 1)

In [11]:
(norm.weights[0], # W
 norm.weights[1]) # b

(DeviceArray([1., 1., 1., 1.], dtype=float32),
 DeviceArray([0., 0., 0., 0.], dtype=float32))

In [12]:
y = norm(x)
y

DeviceArray([-1.3416404 , -0.44721344,  0.44721344,  1.3416404 ], dtype=float32)

### Custom Layers